# Basic
title: Shan's hub
SEOTitle: Shan Jiang -- A salarygirl, daughter & life-learner
header-img: img/home-bg.jpg
email: sj2921@columbia.edu
keyword: Previous New Yorker, a small-town blog writter
welcome_message: Now I am working in TikTok for bridging gaps of Machine Learning models and Business.
description: Hi, I am Shan(@shanjiang21).
url: "https://shanj21.com/"
baseurl: ""

# Publish posts or collection documents with a future date.
future: true

# SNS settings
linkedin_username: shanj21
github_username: shanjiang21
zhihu_username: jiang-shan-59
twitter_username: Alexand43261453

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
#specifies how many items should be displayed per page
paginate_path: "/blog/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Love is a touch <br>and yet not a touch<br>路过人间。"
sidebar-avatar: /img/avatar.jpg

# Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 1             # A tag will be featured if the size of it is more than this condition value

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins:
  - jekyll-paginate
  - jekyll-feed


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false # code chunk
      start_line: 1


# Disqus settings
disqus_username: shanj

# Google Analytics
ga_track_id: 'UA-138327408-1'            # Format: UA-xxxxxx-xx
ga_domain: shanj21.com


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

## Gallery Base URL
#thumbsurl: "../img/thumbs/"
#imagesurl: "../img/"

## SASS configuration
sass:
  sass_dir: _sass
  style: compressed

## Reduce responsive time
exclude:
    - node_modules
